const whiteKill = document.querySelector('.white-kill'),
  blackKill = document.querySelector('.black-kill'),
  whiteKing = document.querySelector('.king.white'),
  blackKing = document.querySelector('.king.black'),
  gameOver = document.querySelector('.game-over');

let allSquares = document.querySelectorAll('.squares'),
  allPieces = document.querySelectorAll('.chess'),
  validIds = [],
  newIds = [],
  checkIds = [],
  newCheckIds = [],
  x,
  y,
  a,
  b,
  c,
  d,
  e,
  f,
  g,
  h,
  firstPawnSquare,
  secondPawnSquare;

let currentSquare,
  current,
  firstSquare,
  secondSquare,
  thirdSquare,
  fourthSquare,
  fifthSquare;
